# render.yaml
services:
  - name: nightscout-librelink-up
    type: worker
    runtime: image
    plan: starter
    image:
      url: timoschlueter/nightscout-librelink-up:latest
    autoDeploy: true
    envVars:
      - key: LINK_UP_USERNAME
        sync: false
      - key: LINK_UP_PASSWORD
        sync: false
      - key: LINK_UP_CONNECTION
        value: ""
      - key: LINK_UP_TIME_INTERVAL
        value: "5"
      - key: LINK_UP_REGION
        value: "EU"
      - key: LINK_UP_VERSION
        value: "4.16.0"
      - key: NIGHTSCOUT_URL
        sync: false
      - key: NIGHTSCOUT_API_TOKEN
        sync: false
      - key: NIGHTSCOUT_DISABLE_HTTPS
        value: "false"
      - key: LOG_LEVEL
        value: "info"
